version: 3.1.5-build{build}
skip_non_tags: true
clone_depth: 1

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

build:
  project: bit7z.vcxproj

matrix:
  fast_finish: true

environment:
  bit7z_version: 3.1.5

  matrix:
  - name: msvc_x86 # MSVC x86
    platform: x86
    fast_finish: true

  - name: msvc_mt_x86 # MSVC x86 MT
    platform: x86
    mt: TRUE
    fast_finish: true

  - name: msvc_x64 # MSVC x64
    platform: x64
    fast_finish: true

  - name: msvc_mt_x64 # MSVC x64 MT
    platform: x64
    mt: TRUE

before_build:
  - ps: Test-Path env:mt
  - ps: if (Test-Path env:mt) {
            ${content} = (Get-Content bit7z.vcxproj);
            ${content} = ${content}.Replace("DLL</RuntimeLibrary>", "</RuntimeLibrary>");
            Set-Content bit7z.vcxproj ${content};
        }
  - git submodule update --init --recursive

build_script:
  - msbuild bit7z.vcxproj /p:configuration=release /p:platform=%platform%
  - msbuild bit7z.vcxproj /p:configuration=debug /p:platform=%platform%

after_build:
  - set msvc_ver=%APPVEYOR_BUILD_WORKER_IMAGE:Visual Studio =msvc%%name:msvc=%
  - mkdir pkg
  - mkdir pkg\bit7z\
  - mkdir pkg\bit7z\lib\
  - mkdir pkg\bit7z\include\
  - copy bin\%platform%\*.* pkg\bit7z\lib\
  - copy include\bit*.hpp pkg\bit7z\include\
  - copy README.md pkg\bit7z\
  - copy LICENSE pkg\bit7z\
  - echo %bit7z_version% %msvc_ver% > pkg\bit7z\BUILD.txt
  - cd pkg
  - 7z a -t7z bit7z-v%bit7z_version%-%msvc_ver%.7z *

artifacts:
  - path: pkg\*.7z
    name: binary

test: off

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Binaries of Bit7z v%bit7z_version%'
  auth_token:
    secure: FXlhX+Nu9dabf4YLycMYx2cAZtJeEOqtRXQ3Qxky32fBQoyt+8xbSzyZFmv0e8ID
  artifact: /.*\.7z/
  draft: true
  prerelease: false
  on:
    # branch: master
    appveyor_repo_tag: true
