version: '0.7.4.{build}'

environment:
    matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
        PRJ_CFG: Release
        PRJ_GEN_VERSION: 12
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015
        PRJ_CFG: Release
        PRJ_GEN_VERSION: 14
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        PRJ_GEN: "Visual Studio 15 2017 Win64"
        BDIR: msvc2017
        PRJ_CFG: Release
        PRJ_GEN_VERSION: 15
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
        PRJ_CFG: Debug
        PRJ_GEN_VERSION: 12
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015
        PRJ_CFG: Debug
        PRJ_GEN_VERSION: 14
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
        PRJ_GEN: "Visual Studio 15 2017 Win64"
        BDIR: msvc2017
        PRJ_CFG: Debug
        PRJ_GEN_VERSION: 15

install:
      - cmd: echo "Downloading conan..."
      - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
      - cmd: pip.exe install conan
      - cmd: conan user # Create the conan data directory
      - cmd: conan --version

build_script:
    - mkdir build.%BDIR%
    - conan install --build=missing -s compiler="Visual Studio" -s compiler.version=%PRJ_GEN_VERSION% -s build_type=%PRJ_CFG% .
    - cd build.%BDIR%
    - cmake .. -G"%PRJ_GEN%"
    - cmake --build . --config %PRJ_CFG% --clean-first


